name: Ladda ner temperaturfil och uppdatera GitHub

on:
  schedule:
    - cron: '*/3 * * * *'  # Kör var tredje minut
  push:
    branches:
      - main  # Kör när du pushar till main

jobs:
  download_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Installera Python och requests
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          pip3 install requests

      - name: Ladda ner och spara temperaturfilen
        run: python3 download_temp_file.py

      - name: Commit och pusha uppdaterad temperaturfil
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Uppdatera temperaturfilen'
          token: ${{ secrets.GH_TOKEN }}  # Använd den skapade tokenen för push-åtkomst
