name: Download and Update Temperatur File

on:
  schedule:
    - cron: '*/3 * * * *'  # Kör var tredje minut
  workflow_dispatch:  # Gör det möjligt att trigga manuellt

jobs:
  download-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Download temperaturfil
      run: curl -o temp.txt http://www.temperatur.nu/termo/pitea-lindbacksstadion/temp.txt

    - name: Commit och pusha uppdaterad temperaturfil
      uses: EndBug/add-and-commit@v7
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Uppdatera temperaturfilen'
        push: true
        branch: main  # Se till att den pushar till rätt branch (här används main)
        add: '.'  # Lägg till alla ändrade filer
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Använd den inbyggda GITHUB_TOKEN
